### ISSUE TITLE
1.20 update question

### ISSUE THREAD

**Issue by vico93** [fooooooooooooooo/WickedPaintings#13]
Sorry to be that guy, but will we be able to have all the wickedness running on 1.20? Are update in the plans?

**Comment by fooooooooooooooo** [comment]
assuming nothing horribly changed in 1.20 that breaks everything, ill update soon

**Comment by V-lpen** [comment]
looking forward to 1.20 update, thank you!! :D

**Comment by vico93** [comment]
![image](https://github.com/fooooooooooooooo/WickedPaintings/assets/3485505/1852ffa6-6ef7-499e-bd05-6f10fffa1e1e)

**Comment by fooooooooooooooo** [comment]
completed in https://github.com/fooooooooooooooo/WickedPaintings/compare/v1.3.2...v1.4.0

**Comment by vico93** [comment]
Thank you so much!
