### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by Multex** [fooooooooooooooo/WickedPaintings#17]
Hey, I want to make a server with my friend but we are using the 1.19.2 version of mc. Is there any chance that you can make the mod compatible with that version? :c

**Comment by fooooooooooooooo** [comment]
same with #15 i didnt see this issue, it might be a little difficult to back port to 1.19.2 but i can still do it if you still need it, reopen if so

**Comment by Multex** [comment]
Still need it, pls 🙏

**Comment by fooooooooooooooo** [comment]
done
https://github.com/fooooooooooooooo/WickedPaintings/releases/tag/v1.4.0-1.19.2

**Comment by Multex** [comment]
noway, thank you so much!!!
