### ISSUE TITLE
Wrong fabric loader?

### ISSUE THREAD

**Issue by vico93** [fooooooooooooooo/WickedPaintings#18]
Hello! I just installed 1.4.1 version for 1.20.4!

But when i try to boot the game i get this strange mod incompatibility warning:
![image](https://github.com/fooooooooooooooo/WickedPaintings/assets/3485505/c0976a30-c750-4d39-9412-2e9acda4d33f)
But from what i understand the latest version of Fabric Loader os 0.15.3 (which is what i have).

**Comment by fooooooooooooooo** [comment]
I put the wrong loader version in fabric.mod.json somehow, I fixed and replaced the downloads on modrinth/github
