### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by TyThePotato** [fooooooooooooooo/WickedPaintings#4]
Lighting
![images jpeg](https://user-images.githubusercontent.com/19415420/158133275-bc940fc0-b618-41b9-9b55-6189e59697c3.jpg)
@fooooooooooooooo

**Comment by bvoo** [comment]
lighting looks fine to me

**Comment by TyThePotato** [comment]
> lighting looks fine to me

No it sucks rely bad sorry it is unlit no shading no lighting its really unrealistic

**Comment by fooooooooooooooo** [comment]
unfortunately i would probably have to rewrite the renderer

**Comment by Spotwich** [comment]
skill issue??!???!??

**Comment by fooooooooooooooo** [comment]
huge i did it
